config/routes.rb
Rails.application.routes.draw do
  get '/', to: 'manufacturers#index'
  resources :manufacturers do
    collection do
      get :list
    end
  end

end

app/models/driver.rb
class Driver < ActiveRecord::Base
  belongs_to :manufacturer
end

app/models/manufacturer.rb
class Manufacturer < ActiveRecord::Base
  has_many :drivers

  validates :name, presence: { message: 'Enter name' }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/manufacturers_controller.rb
class ManufacturersController < ApplicationController
  def index
    @manufacturers = Manufacturer.order('name ASC')
  end

  def show
    @driver = Driver.find(params[:id])
  end

  def new

  end

  def edit

  end

  def update

  end

  def destroy

  end

  def list
    @drivers = Driver # start using the Driver activerecord model
    if params[:manufacturer_id].present?
      @drivers = @drivers.where(manufacturer_id: params[:manufacturer_id])
    end

    if params[:sealed_f3].present?
      @drivers = @drivers.where(sealed_f3: params[:sealed_f3])
    end

    if params[:sealed_volume].present?
      @drivers = @drivers.where(sealed_volume: params[:sealed_volume])
    end

    if params[:rms_power].present?
      @drivers = @drivers.where(rms_power: params[:rms_power])
    end

    if params[:x_max].present?
      @drivers = @drivers.where(x_max: params[:x_max])
    end

    # if params[:ranges].present?
    #   ranges = params[:ranges].split('-') # 100-200
    #   driver = driver.where('power_range BETWEEN ? AND ?', ranges[0], ranges[1])
    # end

    page = (params[:start].to_i / params[:length].to_i) + 1
    @drivers = @drivers.where(driver_search)
    @drivers = @drivers.order(order_list)
    @drivers = @drivers.paginate(page: page, per_page: params[:length])
  end

  private

  def order_list
    column = case params['order']['0']['column']
    when '0' then 'model_no'
    when '1' then 'sealed_f3'
    when '2' then 'sealed_volume'
    when '3' then 'high_frequency_limit'
    when '4' then 'rms_power'
    when '5' then 'x_max'
    else 'model_no'
    end

    dir = params['order']['0']['dir'] == 'asc' ? 'asc' : 'desc'
    [column, dir].join(' ')
  end

  def driver_search
    searched_phrase = params['search']['value'].strip
    return '' if searched_phrase.blank?
    ['LOWER(model_no) LIKE ?', "#{searched_phrase.downcase}%"]
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController

  def search
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/manufacturers_helper.rb
module ManufacturersHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <table id="woofers">
    <thead>
      <title>Woofers</title>
      <%= stylesheet_link_tag    'jquery.dataTables.min.css' %>  
      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
      <%= javascript_include_tag 'jquery-2.1.4.min.js' %>
      <%= javascript_include_tag 'jquery.dataTables.min.js' %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
      <%= csrf_meta_tags %>
    </thead>
    <tbody>

    <%= yield %>

    </tbody>
  </table>
</html>

app/views/manufacturers/index.html.haml
%table#woofers id="woofers" class="display" 
  %thead
    %th model_no
    %th sealed_f3
    %th sealed_volume
    %th high_frequency_limit
    %th rms_power
    %th x_max
  %tbody

= data-source("<%= manufacturers_url(format: "json" %>")
/ = javascript_tag("drivers_table(#{@manufacturers.to_json})")

app/views/manufacturers/list.json.erb
<%
retval = { data: [], recordsFiltered: @drivers.total_entries, recordsTotal: @drivers.total_entries }
@drivers.each do |driver|
  retval[:data] << [
    link_to(driver.model_no, manufacturer_path(driver.id)),
    driver.sealed_f3,
    driver.sealed_volume,
    driver.high_frequency_limit,
    driver.rms_power,
    driver.x_max
  ]
end
%>

<%= retval.to_json %>

app/views/manufacturers/show.html.haml
Show the driver info here:
%br
= @driver.model_no